Repository gpslab/cqrs, pull requests merged in 2020-01, with the labels that each got.

#1 Test enhancement
  .travis.yml
  composer.json
  tests/Command/Bus/HandlerLocatedCommandBusTest.php
  tests/Command/Handler/Locator/ContainerCommandHandlerLocatorTest.php
  tests/Command/Handler/Locator/DirectBindingCommandHandlerLocatorTest.php
  tests/Command/Handler/Locator/SymfonyContainerCommandHandlerLocatorTest.php
  tests/Command/Queue/Pull/MemoryPullCommandQueueTest.php
  tests/Command/Queue/Pull/MemoryUniquePullCommandQueueTest.php
  tests/Command/Queue/Pull/PredisPullCommandQueueTest.php
  tests/Command/Queue/Pull/PredisUniquePullCommandQueueTest.php
  tests/Command/Queue/Serializer/SymfonySerializerTest.php
  tests/Command/Queue/Subscribe/ExecutingSubscribeCommandQueueTest.php
  tests/Command/Queue/Subscribe/PredisSubscribeCommandQueueTest.php
  tests/Query/Bus/HandlerLocatedQueryBusTest.php
  tests/Query/Handler/Locator/ContainerQueryHandlerLocatorTest.php
  tests/Query/Handler/Locator/DirectBindingQueryHandlerLocatorTest.php
  tests/Query/Handler/Locator/SymfonyContainerQueryHandlerLocatorTest.php
Labels: enhancement

#2 Add PHP 7.4 version test
  .travis.yml
  composer.json
  phpunit.xml.dist
  src/Command/Queue/Pull/MemoryUniquePullCommandQueue.php
  src/Command/Queue/Subscribe/ExecutingSubscribeCommandQueue.php
  src/Command/Queue/Subscribe/PredisSubscribeCommandQueue.php
  tests/Command/Bus/HandlerLocatedCommandBusTest.php
  tests/Command/Handler/Locator/ContainerCommandHandlerLocatorTest.php
  tests/Command/Handler/Locator/DirectBindingCommandHandlerLocatorTest.php
  tests/Command/Handler/Locator/SymfonyContainerCommandHandlerLocatorTest.php
  tests/Command/Queue/Pull/MemoryPullCommandQueueTest.php
  tests/Command/Queue/Pull/MemoryUniquePullCommandQueueTest.php
  tests/Command/Queue/Pull/PredisPullCommandQueueTest.php
  tests/Command/Queue/Pull/PredisUniquePullCommandQueueTest.php
  tests/Command/Queue/Serializer/SymfonySerializerTest.php
  tests/Command/Queue/Subscribe/ExecutingSubscribeCommandQueueTest.php
  tests/Command/Queue/Subscribe/PredisSubscribeCommandQueueTest.php
  tests/Query/Bus/HandlerLocatedQueryBusTest.php
  tests/Query/Handler/Locator/ContainerQueryHandlerLocatorTest.php
  tests/Query/Handler/Locator/DirectBindingQueryHandlerLocatorTest.php
  tests/Query/Handler/Locator/SymfonyContainerQueryHandlerLocatorTest.php
Labels: enhancement

#3 Change $this->exactly(1) -> $this->once()
  tests/Command/Handler/Locator/ContainerCommandHandlerLocatorTest.php
  tests/Command/Handler/Locator/SymfonyContainerCommandHandlerLocatorTest.php
  tests/Query/Handler/Locator/ContainerQueryHandlerLocatorTest.php
  tests/Query/Handler/Locator/SymfonyContainerQueryHandlerLocatorTest.php
Labels: bug

#4 Optimize use `will*` methods
  tests/Command/Bus/HandlerLocatedCommandBusTest.php
  tests/Command/Handler/Locator/ContainerCommandHandlerLocatorTest.php
  tests/Command/Handler/Locator/SymfonyContainerCommandHandlerLocatorTest.php
  tests/Command/Queue/Pull/PredisPullCommandQueueTest.php
  tests/Command/Queue/Pull/PredisUniquePullCommandQueueTest.php
  tests/Command/Queue/Serializer/SymfonySerializerTest.php
  tests/Command/Queue/Subscribe/PredisSubscribeCommandQueueTest.php
  tests/Query/Bus/HandlerLocatedQueryBusTest.php
  tests/Query/Handler/Locator/ContainerQueryHandlerLocatorTest.php
  tests/Query/Handler/Locator/SymfonyContainerQueryHandlerLocatorTest.php
Labels: bug

#5 Optimize use assert*() method in tests
  tests/Command/Bus/HandlerLocatedCommandBusTest.php
  tests/Command/Handler/Locator/ContainerCommandHandlerLocatorTest.php
  tests/Command/Handler/Locator/DirectBindingCommandHandlerLocatorTest.php
  tests/Command/Handler/Locator/SymfonyContainerCommandHandlerLocatorTest.php
  tests/Command/Queue/Pull/MemoryPullCommandQueueTest.php
  tests/Command/Queue/Pull/MemoryUniquePullCommandQueueTest.php
  tests/Command/Queue/Pull/PredisPullCommandQueueTest.php
  tests/Command/Queue/Pull/PredisUniquePullCommandQueueTest.php
  tests/Command/Queue/Serializer/SymfonySerializerTest.php
  tests/Command/Queue/Subscribe/ExecutingSubscribeCommandQueueTest.php
  tests/Command/Queue/Subscribe/PredisSubscribeCommandQueueTest.php
  tests/Query/Bus/HandlerLocatedQueryBusTest.php
  tests/Query/Handler/Locator/ContainerQueryHandlerLocatorTest.php
  tests/Query/Handler/Locator/DirectBindingQueryHandlerLocatorTest.php
  tests/Query/Handler/Locator/SymfonyContainerQueryHandlerLocatorTest.php
Labels: bug

#6 Declare type hinting
  docs/command/handler.md
  docs/command/locator/direct_binding.md
  docs/command/locator/psr-11_container.md
  docs/command/locator/symfony_container.md
  docs/command/queue/queue.md
  docs/command/queue/serialize/optimized.md
  docs/command/queue/serialize/payload.md
  docs/command/queue/subscribe/executing.md
  docs/command/queue/subscribe/predis.md
  docs/command/simple_usage.md
  docs/query/handler.md
  docs/query/locator/direct_binding.md
  docs/query/locator/psr-11_container.md
  docs/query/simple_usage.md
  src/Command/Bus/CommandBus.php
  src/Command/Bus/HandlerLocatedCommandBus.php
  src/Command/Exception/HandlerNotFoundException.php
  src/Command/Handler/Locator/CommandHandlerLocator.php
  src/Command/Handler/Locator/ContainerCommandHandlerLocator.php
  src/Command/Handler/Locator/DirectBindingCommandHandlerLocator.php
  src/Command/Handler/Locator/SymfonyContainerCommandHandlerLocator.php
  src/Command/Queue/CommandQueue.php
  src/Command/Queue/Pull/MemoryPullCommandQueue.php
  src/Command/Queue/Pull/MemoryUniquePullCommandQueue.php
  src/Command/Queue/Pull/PredisPullCommandQueue.php
  src/Command/Queue/Pull/PredisUniquePullCommandQueue.php
  src/Command/Queue/Pull/PullCommandQueue.php
  src/Command/Queue/Serializer/Serializer.php
  src/Command/Queue/Serializer/SymfonySerializer.php
  src/Command/Queue/Subscribe/ExecutingSubscribeCommandQueue.php
  src/Command/Queue/Subscribe/PredisSubscribeCommandQueue.php
  src/Command/Queue/Subscribe/SubscribeCommandQueue.php
  src/Query/Bus/HandlerLocatedQueryBus.php
  src/Query/Exception/HandlerNotFoundException.php
  src/Query/Handler/Locator/ContainerQueryHandlerLocator.php
  src/Query/Handler/Locator/DirectBindingQueryHandlerLocator.php
  src/Query/Handler/Locator/QueryHandlerLocator.php
  src/Query/Handler/Locator/SymfonyContainerQueryHandlerLocator.php
  tests/Command/Bus/HandlerLocatedCommandBusTest.php
  tests/Command/Handler/Locator/ContainerCommandHandlerLocatorTest.php
  tests/Command/Handler/Locator/DirectBindingCommandHandlerLocatorTest.php
  tests/Command/Handler/Locator/SymfonyContainerCommandHandlerLocatorTest.php
  tests/Command/Queue/Pull/MemoryPullCommandQueueTest.php
  tests/Command/Queue/Pull/MemoryUniquePullCommandQueueTest.php
  tests/Command/Queue/Pull/PredisPullCommandQueueTest.php
  tests/Command/Queue/Pull/PredisUniquePullCommandQueueTest.php
  tests/Command/Queue/Serializer/SymfonySerializerTest.php
  tests/Command/Queue/Subscribe/ExecutingSubscribeCommandQueueTest.php
  tests/Command/Queue/Subscribe/PredisSubscribeCommandQueueTest.php
  tests/Fixture/Command/Handler/CreateContactHandler.php
  tests/Fixture/Command/Handler/RenameContactHandler.php
  tests/Fixture/Query/Handler/ContactByIdentityHandler.php
  tests/Fixture/Query/Handler/ContactByNameHandler.php
  tests/Query/Bus/HandlerLocatedQueryBusTest.php
  tests/Query/Handler/Locator/ContainerQueryHandlerLocatorTest.php
  tests/Query/Handler/Locator/DirectBindingQueryHandlerLocatorTest.php
  tests/Query/Handler/Locator/SymfonyContainerQueryHandlerLocatorTest.php
Labels: feature

#7 Not use a call_user_func() function
  tests/Command/Handler/Locator/ContainerCommandHandlerLocatorTest.php
  tests/Command/Handler/Locator/SymfonyContainerCommandHandlerLocatorTest.php
  tests/Query/Handler/Locator/ContainerQueryHandlerLocatorTest.php
Labels: bug

#8 Change PHP-CS-Fixer rules
  .php_cs.dist
  src/Command/Bus/HandlerLocatedCommandBus.php
  tests/Command/Bus/HandlerLocatedCommandBusTest.php
  tests/Command/Handler/Locator/ContainerCommandHandlerLocatorTest.php
  tests/Command/Handler/Locator/DirectBindingCommandHandlerLocatorTest.php
  tests/Command/Handler/Locator/SymfonyContainerCommandHandlerLocatorTest.php
  tests/Command/Queue/Pull/PredisPullCommandQueueTest.php
  tests/Command/Queue/Pull/PredisUniquePullCommandQueueTest.php
  tests/Command/Queue/Serializer/SymfonySerializerTest.php
  tests/Command/Queue/Subscribe/PredisSubscribeCommandQueueTest.php
  tests/Query/Bus/HandlerLocatedQueryBusTest.php
  tests/Query/Handler/Locator/ContainerQueryHandlerLocatorTest.php
  tests/Query/Handler/Locator/SymfonyContainerQueryHandlerLocatorTest.php
  tests/bootstrap.php
Labels: feature

#10 Copy rules from PHP CS Fixer to Style CI config
  .styleci.yml
Labels: bug

#11 Apply fixes from StyleCI
  src/Command/Queue/Pull/MemoryUniquePullCommandQueue.php
  src/Command/Queue/Subscribe/ExecutingSubscribeCommandQueue.php
  src/Command/Queue/Subscribe/PredisSubscribeCommandQueue.php
Labels: bug

#12 Add Command and Query subscribers
  docs/command/locator/direct_binding.md
  docs/command/locator/psr-11_container.md
  docs/command/locator/symfony_container.md
  docs/query/locator/direct_binding.md
  docs/query/locator/psr-11_container.md
  docs/query/locator/symfony_container.md
  src/Command/Handler/CommandSubscriber.php
  src/Command/Handler/Locator/ContainerCommandHandlerLocator.php
  src/Command/Handler/Locator/DirectBindingCommandHandlerLocator.php
  src/Command/Handler/Locator/SymfonyContainerCommandHandlerLocator.php
  src/Query/Handler/Locator/ContainerQueryHandlerLocator.php
  src/Query/Handler/Locator/DirectBindingQueryHandlerLocator.php
  src/Query/Handler/Locator/SymfonyContainerQueryHandlerLocator.php
  src/Query/Handler/QuerySubscriber.php
  tests/Command/Handler/Locator/ContainerCommandHandlerLocatorTest.php
  tests/Command/Handler/Locator/DirectBindingCommandHandlerLocatorTest.php
  tests/Command/Handler/Locator/SymfonyContainerCommandHandlerLocatorTest.php
  tests/Fixture/Command/Handler/ContestCommandSubscriber.php
  tests/Fixture/Query/Handler/ContestQuerySubscriber.php
  tests/Query/Handler/Locator/ContainerQueryHandlerLocatorTest.php
  tests/Query/Handler/Locator/DirectBindingQueryHandlerLocatorTest.php
  tests/Query/Handler/Locator/SymfonyContainerQueryHandlerLocatorTest.php
Labels: feature

#13 Test coverage only once
  .travis.yml
Labels: bug

#15 Update 2.0 from master
  .travis.yml
Labels: bug

#16 Copy simple usage docs in main README.md
  README.md
  docs/command/simple_usage.md
  docs/query/simple_usage.md
Labels: feature

#17 Require PHPStan for Static Analysis PHP
  .travis.yml
  composer.json
  phpstan.neon.dist
  tests/Command/Queue/Subscribe/PredisSubscribeCommandQueueTest.php
Labels: feature

#18 Fix missing iterable value type for PHPStan
  composer.json
  phpstan.neon.dist
  src/Command/Handler/CommandSubscriber.php
  src/Command/Handler/Locator/ContainerCommandHandlerLocator.php
  src/Command/Handler/Locator/SymfonyContainerCommandHandlerLocator.php
  src/Command/Queue/Pull/PredisPullCommandQueue.php
  src/Command/Queue/Pull/PredisUniquePullCommandQueue.php
  src/Query/Handler/Locator/ContainerQueryHandlerLocator.php
  src/Query/Handler/Locator/SymfonyContainerQueryHandlerLocator.php
  src/Query/Handler/QuerySubscriber.php
  tests/Command/Queue/Pull/PredisPullCommandQueueTest.php
  tests/Command/Queue/Pull/PredisUniquePullCommandQueueTest.php
  tests/Command/Queue/Serializer/SymfonySerializerTest.php
  tests/Fixture/Command/Handler/ContestCommandSubscriber.php
  tests/Fixture/Query/Handler/ContestQuerySubscriber.php
Labels: feature

#19 Use phar of Scrutinizer CI and PHP Coveralls
  .travis.yml
  .travis/predis_10_phpstan.neon
  composer.json
Labels: feature

#20 PHPStan level 7
  phpstan.neon.dist
  src/Command/Handler/Locator/ContainerCommandHandlerLocator.php
  src/Command/Handler/Locator/DirectBindingCommandHandlerLocator.php
  src/Command/Handler/Locator/SymfonyContainerCommandHandlerLocator.php
  src/Command/Queue/Serializer/SymfonySerializer.php
  src/Query/Handler/Locator/ContainerQueryHandlerLocator.php
  src/Query/Handler/Locator/DirectBindingQueryHandlerLocator.php
  src/Query/Handler/Locator/SymfonyContainerQueryHandlerLocator.php
Labels: bug

#22 Test with Symfony 3.4, 4.4, 5.0
  .travis.yml
Labels: feature
